give @s normaconstructor:choose_next_generator
give @s normaconstructor:execute
give @s normaconstructor:get_air
give @s normaconstructor:get_position
give @s normaconstructor:get_direction
give @s normaconstructor:remove_last_position
give @s normaconstructor:remove_last_direction
give @s normaconstructor:remove_last_blocktype
give @s normaconstructor:show_menu
give @s normaconstructor:show_meta_menu
give @s normaconstructor:show_saved_data